// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Feralas;

#nullable disable

namespace Feralas.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20220827080033_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Feralas.WowAuction", b =>
                {
                    b.Property<long>("PrimaryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuctionId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Buyout")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedRealmId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShortTimeLeftSeen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sold")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrimaryKey");

                    b.ToTable("WowAuctions");
                });

            modelBuilder.Entity("Feralas.WowItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonusList")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PetBreedId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PetLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PetQualityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PetSpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WowItems");
                });
#pragma warning restore 612, 618
        }
    }
}
